# name: Dependency-Track Scan

# on:
#   push:
#     branches:
#       - dev
#   pull_request:

# jobs:
#   dependency-track:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v4

#       - name: Generate SBOM with CycloneDX
#         run: |
#           pip install cyclonedx-bom
#           cyclonedx-py environment --outfile my-sbom.xml --schema-version 1.6 --output-format XML

#       - name: Upload SBOM to Dependency-Track
#         uses: DependencyTrack/gh-upload-sbom@v3
#         with:
#           serverHostname: ' ${{ secrets.DTRACK_SERVER_HOSTNAME }}'
#           apiKey: ${{ secrets.DEPENDENCYTRACK_APIKEY }}
#           projectName: 'devsecops2'
#           projectVersion: 'main'
#           bomFilename: "my-sbom.xml"
#           autoCreate: true
#           protocol: http
#           port : 8080
